### ISSUE TITLE
prebuilt binaries?

### ISSUE THREAD

**Issue by cboettig** [isaacbrodsky/h3-duckdb#91]
Thanks for providing this amazing extension, it works wonderfully and provides a very valuable set of features!  

Apologies if this is a silly question, but is it possible to distribute this extension as a pre-built binary, like other extensions in duckdb? If so, is that on your road map at some point?

**Comment by isaacbrodsky** [comment]
Hi -- thanks and glad you find it useful.

It's on my TODO list to provide a hosted version of the extension, hosted on e.g. S3 or R2 or something. The binaries are built in CI, I just haven't gotten around to getting them uploaded somewhere yet.

Unfortunately it will still not be possible to load the extension without running DuckDB with `unsigned` mode. This is because DuckDB enforces signature validation, but has no mechanism for third-party extensions like this one to get signed.

**Comment by cboettig** [comment]
sounds great, thanks!  

Re hosting, could the binaries be published as github release objects (or via github container registry, like [homebrew does](https://betterprogramming.pub/how-homebrew-serves-52m-packages-per-month-413b9f0cf685))?  Just a thought, since I know S3 has direct costs.

Good point about the signature issue, I'll check in with duckdb team to see if a third-party signature mechanism is on the road map.  

(just did a duckdb-h3 demo for my grad class today, went very well!)
